spring:
  application:
    name: techchallenge01
  datasource:
    url: jdbc:postgresql://localhost:5432/techchallenge
    username: "root"
    password: "m@_ssq@HJ7<h(+"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: alpha
    docExpansion: none
tag:
  swagger:
    cliente:
        name: "Cliente"
        description: "API de Clientes"


