spring:
  application:
    name: techchallenge01
  datasource:
    url: jdbc:postgresql://localhost:5432/techchallenge
    username: "root"
    password: "m@_ssq@HJ7<h(+"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method


