name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Login to DockerHub
        run: docker login -u alecigolini -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t alecigolini/fiap-techchallenge01 .
          docker push alecigolini/fiap-techchallenge01