name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fiap-techchallenge01:$(date +%s)

    - uses: docker/login-action@v3.3.0
    - name: Docker Login
      with:
          username: aleCigolini
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: aleCigolini/fiap-techchallenge01
        username: aleCigolini
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
